name: Pipeline

on: "push"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Compile Typecript
        run: npm run build

      - name: Run Linter
        run: npm run lint
